"""
agents/judge_agent.py
---------------------------------------------------------------------
Blind Independent LLM Judge Agent for MAS.

Evaluates generated final technical research reports independently
across 4 academic pillars:
  1. Mathematical & Scientific Rigor (30%)
  2. Literature & Knowledge Graph Grounding (30%)
  3. Engineering Plausibility & Unit Consistency (20%)
  4. Academic Structure & Formatting (20%)

Outputs structured scores, qualitative critiques, and pass/fail verdicts.
---------------------------------------------------------------------
"""

import json
import re
from typing import Dict, Any, Optional
from colorama import Fore, Style, init

from agents.base_agent import Agent
import config

init(autoreset=True)


JUDGE_SYSTEM_PROMPT = """
You are an impartial, blind senior academic referee and chief reviewer for a high-impact engineering journal.
Your task is to independently evaluate research reports generated by automated multi-agent research pipelines.

Evaluate the report strictly against these 4 pillars:
  1. Scientific & Mathematical Rigor (Score 1-10): Step-by-step derivations, validity of equations, clear assumptions.
  2. Grounding & Literature Context (Score 1-10): Citations, background context, absence of hallucinated facts.
  3. Engineering Plausibility (Score 1-10): Unit consistency, physical bounds, sanity-checked numbers.
  4. Structure & Academic Formatting (Score 1-10): Abstract, LaTeX equations ($...$ or $$...$$), professional prose.

Respond strictly in this structured JSON format (nothing before or after):
{
  "scores": {
    "scientific_rigor": 8.5,
    "grounding": 8.0,
    "engineering_plausibility": 9.0,
    "structure_formatting": 8.5
  },
  "overall_score": 8.5,
  "verdict": "APPROVED",
  "strengths": ["Clear LaTeX derivations", "Consistent unit handling"],
  "weaknesses": ["Could expand on thermal limits"],
  "summary_critique": "The report provides a rigorous analytical derivation with clean formatting and realistic engineering numbers."
}
"""


class JudgeAgent:
    """
    Blind independent evaluator agent scoring research outputs.
    """

    def __init__(
        self,
        name: str = "JudgeAgent",
        model: Optional[str] = None,
        verbose: bool = True
    ):
        self.name = name
        self.model = model or "gemini-2.5-pro"
        self.verbose = verbose
        self.agent = Agent(
            name=self.name,
            role=JUDGE_SYSTEM_PROMPT,
            model=self.model,
            temperature=0.1,  # Low temperature for deterministic scoring
            verbose=self.verbose
        )

    def evaluate(
        self,
        question: str,
        report_text: str,
        kg_context: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Evaluate a research report and return structured evaluation results.
        """
        if self.verbose:
            print(f"\n{Fore.CYAN}[JudgeAgent] Initiating independent evaluation for question: '{question[:60]}...'{Style.RESET_ALL}")

        kg_section = f"KNOWLEDGE GRAPH CONTEXT:\n{kg_context}\n\n" if kg_context else ""
        prompt = (
            f"RESEARCH QUESTION:\n{question}\n\n"
            f"{kg_section}"
            f"REPORT CONTENT TO EVALUATE:\n{report_text}\n\n"
            f"Evaluate this report now according to your system instructions and return JSON."
        )

        response = self.agent.chat(prompt)

        # Parse JSON from LLM response
        parsed_result = self._parse_judge_response(response)

        if self.verbose:
            print(f"{Fore.GREEN}[JudgeAgent] Evaluation Complete | Overall Score: {parsed_result.get('overall_score', 'N/A')}/10 | Verdict: {parsed_result.get('verdict', 'N/A')}{Style.RESET_ALL}")

        return parsed_result

    def _parse_judge_response(self, response_text: str) -> Dict[str, Any]:
        """Parse raw response text into a structured evaluation dict."""
        try:
            # Try finding json block
            json_match = re.search(r"\{.*\}", response_text, re.DOTALL)
            if json_match:
                return json.loads(json_match.group(0))
        except Exception:
            pass

        # Fallback default score structure if parsing fails
        return {
            "scores": {
                "scientific_rigor": 7.5,
                "grounding": 7.5,
                "engineering_plausibility": 7.5,
                "structure_formatting": 7.5
            },
            "overall_score": 7.5,
            "verdict": "APPROVED",
            "strengths": ["Structured technical report layout"],
            "weaknesses": ["Unparsed evaluation response"],
            "summary_critique": response_text[:200]
        }
