"""
agents/judge_agent.py
---------------------------------------------------------------------
Blind Independent LLM Judge Agent for MAS.

Stateless quality-control evaluator for final research reports across 4 academic pillars:
  1. Scientific & Mathematical Rigor (30%)
  2. Literature & Grounding Context (30%)
  3. Engineering Plausibility & Unit Consistency (20%)
  4. Academic Structure & Formatting (20%)

Outputs validated structured JSON with zero memory side effects.
---------------------------------------------------------------------
"""

import json
import re
from typing import Dict, Any, Optional
from colorama import Fore, Style, init
import config

init(autoreset=True)


JUDGE_SYSTEM_PROMPT = """
You are an impartial, blind senior academic referee and chief reviewer for a high-impact engineering journal.
Your task is to independently evaluate final technical research reports generated by automated research pipelines.

Evaluate the report strictly against these 4 pillars:
  1. Scientific & Mathematical Rigor (Score 1-10): Step-by-step derivations, validity of equations, clear assumptions.
  2. Grounding & Literature Context (Score 1-10): Citations, background context, absence of hallucinated facts.
  3. Engineering Plausibility (Score 1-10): Unit consistency, physical bounds, sanity-checked numbers.
  4. Structure & Academic Formatting (Score 1-10): Abstract, LaTeX equations ($...$ or $$...$$), professional prose.

Respond strictly in this structured JSON format (nothing before or after):
{
  "scores": {
    "scientific_rigor": 8.5,
    "grounding": 8.0,
    "engineering_plausibility": 9.0,
    "structure_formatting": 8.5
  },
  "overall_score": 8.5,
  "verdict": "APPROVED",
  "strengths": ["Clear LaTeX derivations", "Consistent unit handling"],
  "weaknesses": ["Could expand on thermal limits"],
  "summary_critique": "The report provides a rigorous analytical derivation with clean formatting and realistic engineering numbers."
}
"""


class JudgeAgent:
    """
    Stateless independent evaluator agent scoring research outputs.
    Fully isolated from Working Memory and Knowledge Graph side effects.
    """

    def __init__(
        self,
        name: str = "JudgeAgent",
        provider: str = "gemini",
        model: Optional[str] = None,
        verbose: bool = True
    ):
        self.name = name
        self.provider = provider
        self.model = model or config.DEFAULT_MODEL
        self.verbose = verbose

    def evaluate(
        self,
        question: str,
        report_text: str,
        evidence_context: Optional[str] = None,
        kg_context: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Evaluate a research report statelessly and return structured evaluation results.
        Does NOT modify WorkingMemory, LongTermMemory, or Knowledge Graph.
        """
        if self.verbose:
            print(f"\n{Fore.CYAN}[JudgeAgent] Initiating stateless evaluation for question: '{question[:60]}...'{Style.RESET_ALL}")

        context_str = evidence_context or kg_context or ""
        evidence_section = f"RESEARCH EVIDENCE & CONTEXT:\n{context_str}\n\n" if context_str else ""

        prompt = (
            f"RESEARCH QUESTION:\n{question}\n\n"
            f"{evidence_section}"
            f"REPORT CONTENT TO EVALUATE:\n{report_text}\n\n"
            f"Evaluate this report now according to your system instructions and return strict JSON."
        )

        messages = [
            {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
            {"role": "user", "content": prompt}
        ]

        # Call provider statelessly
        response_text = config.call_with_fallback(
            messages=messages,
            primary_provider=self.provider,
            primary_model=self.model,
            fallback_provider="gemini",
            fallback_model=config.GEMINI_RESEARCH_MODEL,
            temperature=0.1,
            max_tokens=2000
        )

        # Step 1: Attempt JSON parse
        parsed_result = self._parse_json(response_text)

        # Step 2: One-shot retry if initial parse failed
        if not parsed_result:
            if self.verbose:
                print(f"{Fore.YELLOW}[JudgeAgent] Initial JSON parse failed. Executing one-shot retry...{Style.RESET_ALL}")

            retry_messages = messages + [
                {"role": "assistant", "content": response_text},
                {"role": "user", "content": "Your previous response was not valid JSON. Please output ONLY the raw JSON object matching the required schema."}
            ]

            retry_text = config.call_with_fallback(
                messages=retry_messages,
                primary_provider=self.provider,
                primary_model=self.model,
                fallback_provider="gemini",
                fallback_model=config.GEMINI_RESEARCH_MODEL,
                temperature=0.1,
                max_tokens=2000
            )

            parsed_result = self._parse_json(retry_text)

        # Step 3: If still invalid or API error, return structured JUDGE_ERROR (NEVER fake 7.5 APPROVED)
        if not parsed_result:
            if self.verbose:
                print(f"{Fore.RED}[JudgeAgent] Evaluation failed. Returning structured JUDGE_ERROR.{Style.RESET_ALL}")
            return {
                "success": False,
                "scores": {
                    "scientific_rigor": 0.0,
                    "grounding": 0.0,
                    "engineering_plausibility": 0.0,
                    "structure_formatting": 0.0
                },
                "overall_score": 0.0,
                "verdict": "JUDGE_ERROR",
                "strengths": [],
                "weaknesses": ["Evaluation output was invalid JSON or provider failed."],
                "summary_critique": "Failed to parse structured evaluation JSON after retry."
            }

        # Step 4: Validate score & verdict consistency
        parsed_result["success"] = True
        parsed_result = self._validate_verdict(parsed_result)

        if self.verbose:
            print(f"{Fore.GREEN}[JudgeAgent] Evaluation Complete | Overall Score: {parsed_result.get('overall_score', 'N/A')}/10 | Verdict: {parsed_result.get('verdict', 'N/A')}{Style.RESET_ALL}")

        return parsed_result

    def _parse_json(self, text: str) -> Optional[Dict[str, Any]]:
        """Safely extract and parse JSON object from LLM response string."""
        if not text or not isinstance(text, str):
            return None

        # Check for provider error indicators
        if "[LLM" in text or "[Groq" in text or "[Gemini" in text or "429" in text:
            return None

        try:
            json_match = re.search(r"\{.*\}", text, re.DOTALL)
            if json_match:
                data = json.loads(json_match.group(0))
                if isinstance(data, dict) and ("scores" in data or "overall_score" in data) and "verdict" in data:
                    return data
        except Exception:
            pass

        return None

    def _validate_verdict(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Enforce score-verdict consistency."""
        overall = float(data.get("overall_score", 0.0))
        verdict = str(data.get("verdict", "")).upper()

        if overall < 6.0 and verdict == "APPROVED":
            data["verdict"] = "REJECT"
        elif overall < 8.0 and verdict == "APPROVED":
            data["verdict"] = "REVISE"

        return data
